### ISSUE TITLE
logrus/Sirupsen Import

### ISSUE THREAD

**Issue by Rossiar** [polds/logrus-papertrail-hook#11]
All import statements of `"github.com/Sirupsen/logrus"` cause this error for us:

`case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"`

The repository is called https://github.com/sirupsen/logrus not Sirupsen, not sure if the name changed or what, but I am going to PR to lowercase it.

**Comment by undiabler** [comment]
You are right. There was a big confusing problem with this renamings.
There is already v3 tag with lowercase. 

you can make PR with updates to master. 

see #8
