### ISSUE TITLE
Current build seems to be failing

### ISSUE THREAD

**Issue by JJ** [polds/logrus-papertrail-hook#4]
Check it out at https://travis-ci.org/polds/logrus-papertrail-hook/jobs/145635574

**Comment by polds** [comment]
Looks like it's not a huge deal: https://github.com/polds/logrus-papertrail-hook/blob/master/papertrail_test.go#L56 its expecting a papertrail host/port combination to be set in the environment which the build does not have.

I'll look into porting it to a self hosted TCP server for the tests.

**Comment by undiabler** [comment]
Made fake tcp request via conn interface https://github.com/polds/logrus-papertrail-hook/pull/5
I think it will be enough. In hook module we shoud test only if fire function works as expected. 
Testing full tcp/upd connect with sending data is superfluously. There are tests in dial package.

**Comment by polds** [comment]
@undiabler that looks good to me, thank you. Merged.
